all:
  hosts:
    my_server:
      ansible_host: 172.16.131.129
      ansible_user: ubuntu
      ansible_become: yes
      ansible_become_user: ubuntu
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  vars:
    ansible_python_interpreter: /usr/bin/python3