all:
  hosts:
    my_server:
    # Vm ubuntu 1
      ansible_host: 172.16.131.131
    # Vm ubuntu 2
#      ansible_host: 172.16.131.130
    # Vm ubuntu 3
#      ansible_host: 172.16.131.130
    # Vm ubuntu 4
#      ansible_host: 172.16.131.130
      ansible_user: ubuntu
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  vars:
    ansible_python_interpreter: /usr/bin/python3