- name: Create New User and Setup System
  hosts: all
  become: true
  gather_facts: true
  vars:
    username: codingfactory
    userpass: codingfactory
    server_description: 'vm ubuntu ansible'
    project_name: 'ansible tp1'
  tasks:

    - name: Ensure user "{{ username }}" exists
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ userpass | password_hash('sha512') }}"
        shell: /bin/bash
        update_password: on_create

    - name: Deploy SSH Public Key for "{{ username }}"
      ansible.builtin.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', 'keys/mathieu.pub') }}"

    - name: Add user to sudoers
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/{{ username }}
        line: '{{ username }} ALL=(ALL) NOPASSWD:ALL'
        create: yes
        validate: 'visudo -cf %s'

    - name: Deploy Message of the Day
      ansible.builtin.template:
        src: templates/motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'

    - name: Execute MariaDB installation playbook
      include_tasks: db.yml

#    - name: Execute SSH check playbook
#      import_playbook: check_ssh.yml
