name: Ansible Playbook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible
        pip install passlib

    - name: Run Ansible Playbook
      run: echo ${{ secrets.SUDO_PASSWORD }} | ansible-playbook ansible_tp1/system.yml -i ansible_tp1/hosts.yml --ask-become-pass
      env:
        ANSIBLE_BECOME_METHOD: sudo
        ANSIBLE_BECOME: true
        ANSIBLE_BECOME_USER: root
